/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingPrerequisitesRouteImport } from './routes/onboarding-prerequisites'
import { Route as IndexRouteImport } from './routes/index'

const OnboardingPrerequisitesRoute = OnboardingPrerequisitesRouteImport.update({
  id: '/onboarding-prerequisites',
  path: '/onboarding-prerequisites',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/onboarding-prerequisites': typeof OnboardingPrerequisitesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding-prerequisites': typeof OnboardingPrerequisitesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/onboarding-prerequisites': typeof OnboardingPrerequisitesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/onboarding-prerequisites'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/onboarding-prerequisites'
  id: '__root__' | '/' | '/onboarding-prerequisites'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OnboardingPrerequisitesRoute: typeof OnboardingPrerequisitesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding-prerequisites': {
      id: '/onboarding-prerequisites'
      path: '/onboarding-prerequisites'
      fullPath: '/onboarding-prerequisites'
      preLoaderRoute: typeof OnboardingPrerequisitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OnboardingPrerequisitesRoute: OnboardingPrerequisitesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
