/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingPrerequisitesRouteImport } from './routes/onboarding-prerequisites'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as ProjectsRepoIdRouteImport } from './routes/projects.$repoId'
import { Route as ProjectsRepoIdIndexRouteImport } from './routes/projects.$repoId.index'
import { Route as ProjectsRepoIdCodeRouteImport } from './routes/projects.$repoId.code'
import { Route as ProjectsRepoIdExtensionsExtensionIdRouteImport } from './routes/projects.$repoId.extensions.$extensionId'

const OnboardingPrerequisitesRoute = OnboardingPrerequisitesRouteImport.update({
  id: '/onboarding-prerequisites',
  path: '/onboarding-prerequisites',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRepoIdRoute = ProjectsRepoIdRouteImport.update({
  id: '/projects/$repoId',
  path: '/projects/$repoId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRepoIdIndexRoute = ProjectsRepoIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsRepoIdRoute,
} as any)
const ProjectsRepoIdCodeRoute = ProjectsRepoIdCodeRouteImport.update({
  id: '/code',
  path: '/code',
  getParentRoute: () => ProjectsRepoIdRoute,
} as any)
const ProjectsRepoIdExtensionsExtensionIdRoute =
  ProjectsRepoIdExtensionsExtensionIdRouteImport.update({
    id: '/extensions/$extensionId',
    path: '/extensions/$extensionId',
    getParentRoute: () => ProjectsRepoIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/onboarding-prerequisites': typeof OnboardingPrerequisitesRoute
  '/projects/$repoId': typeof ProjectsRepoIdRouteWithChildren
  '/projects/': typeof ProjectsIndexRoute
  '/projects/$repoId/code': typeof ProjectsRepoIdCodeRoute
  '/projects/$repoId/': typeof ProjectsRepoIdIndexRoute
  '/projects/$repoId/extensions/$extensionId': typeof ProjectsRepoIdExtensionsExtensionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding-prerequisites': typeof OnboardingPrerequisitesRoute
  '/projects': typeof ProjectsIndexRoute
  '/projects/$repoId/code': typeof ProjectsRepoIdCodeRoute
  '/projects/$repoId': typeof ProjectsRepoIdIndexRoute
  '/projects/$repoId/extensions/$extensionId': typeof ProjectsRepoIdExtensionsExtensionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/onboarding-prerequisites': typeof OnboardingPrerequisitesRoute
  '/projects/$repoId': typeof ProjectsRepoIdRouteWithChildren
  '/projects/': typeof ProjectsIndexRoute
  '/projects/$repoId/code': typeof ProjectsRepoIdCodeRoute
  '/projects/$repoId/': typeof ProjectsRepoIdIndexRoute
  '/projects/$repoId/extensions/$extensionId': typeof ProjectsRepoIdExtensionsExtensionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding-prerequisites'
    | '/projects/$repoId'
    | '/projects/'
    | '/projects/$repoId/code'
    | '/projects/$repoId/'
    | '/projects/$repoId/extensions/$extensionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding-prerequisites'
    | '/projects'
    | '/projects/$repoId/code'
    | '/projects/$repoId'
    | '/projects/$repoId/extensions/$extensionId'
  id:
    | '__root__'
    | '/'
    | '/onboarding-prerequisites'
    | '/projects/$repoId'
    | '/projects/'
    | '/projects/$repoId/code'
    | '/projects/$repoId/'
    | '/projects/$repoId/extensions/$extensionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OnboardingPrerequisitesRoute: typeof OnboardingPrerequisitesRoute
  ProjectsRepoIdRoute: typeof ProjectsRepoIdRouteWithChildren
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding-prerequisites': {
      id: '/onboarding-prerequisites'
      path: '/onboarding-prerequisites'
      fullPath: '/onboarding-prerequisites'
      preLoaderRoute: typeof OnboardingPrerequisitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$repoId': {
      id: '/projects/$repoId'
      path: '/projects/$repoId'
      fullPath: '/projects/$repoId'
      preLoaderRoute: typeof ProjectsRepoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$repoId/': {
      id: '/projects/$repoId/'
      path: '/'
      fullPath: '/projects/$repoId/'
      preLoaderRoute: typeof ProjectsRepoIdIndexRouteImport
      parentRoute: typeof ProjectsRepoIdRoute
    }
    '/projects/$repoId/code': {
      id: '/projects/$repoId/code'
      path: '/code'
      fullPath: '/projects/$repoId/code'
      preLoaderRoute: typeof ProjectsRepoIdCodeRouteImport
      parentRoute: typeof ProjectsRepoIdRoute
    }
    '/projects/$repoId/extensions/$extensionId': {
      id: '/projects/$repoId/extensions/$extensionId'
      path: '/extensions/$extensionId'
      fullPath: '/projects/$repoId/extensions/$extensionId'
      preLoaderRoute: typeof ProjectsRepoIdExtensionsExtensionIdRouteImport
      parentRoute: typeof ProjectsRepoIdRoute
    }
  }
}

interface ProjectsRepoIdRouteChildren {
  ProjectsRepoIdCodeRoute: typeof ProjectsRepoIdCodeRoute
  ProjectsRepoIdIndexRoute: typeof ProjectsRepoIdIndexRoute
  ProjectsRepoIdExtensionsExtensionIdRoute: typeof ProjectsRepoIdExtensionsExtensionIdRoute
}

const ProjectsRepoIdRouteChildren: ProjectsRepoIdRouteChildren = {
  ProjectsRepoIdCodeRoute: ProjectsRepoIdCodeRoute,
  ProjectsRepoIdIndexRoute: ProjectsRepoIdIndexRoute,
  ProjectsRepoIdExtensionsExtensionIdRoute:
    ProjectsRepoIdExtensionsExtensionIdRoute,
}

const ProjectsRepoIdRouteWithChildren = ProjectsRepoIdRoute._addFileChildren(
  ProjectsRepoIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OnboardingPrerequisitesRoute: OnboardingPrerequisitesRoute,
  ProjectsRepoIdRoute: ProjectsRepoIdRouteWithChildren,
  ProjectsIndexRoute: ProjectsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
